//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NuWriter.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PACK_TAB1                   101
#define IDD_NUWRITER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_SPI                         129
#define IDD_SDRAM                       130
#define IDD_TARGET_CHIP                 131
#define IDD_MMC                         132
#define IDI_CHIP                        133
#define IDD_NAND                        133
#define IDD_MTP                         134
#define IDD_INIT                        135
#define IDB_BITMAP1                     140
#define IDB_BANNER                      140
#define IDB_READ_DEVICE                 141
#define IDB_WRITE_DEVICE                142
#define IDB_BITMAP2                     143
#define IDB_BROWSE                      143
#define IDB_FORMAT                      144
#define IDB_ERASEALL                    145
#define IDB_VERIFY                      146
#define IDB_CONTINUE                    148
#define IDB_RECONNECT0                  149
#define IDB_BITMAP4                     150
#define IDB_RECONNECT1                  150
#define IDB_EXIT                        151
#define IDB_NUWRITER                    152
#define IDD_SPI_READ                    154
#define IDD_READ                        154
#define IDD_PACK                        155
#define IDB_ADD                         155
#define IDB_DELETE                      156
#define IDB_BITMAP3                     157
#define IDB_MODIFY                      157
#define IDB_BITMAP5                     158
#define IDB_OUTPUT                      158
#define IDD_DIALOG1                     159
#define IDD_FORMAT                      159
#define IDC_PACK_TAB2                   160
#define IDD_PACK_TAB2                   160
#define IDD_ERASE                       163
#define IDD_FAST                        164
#define IDD_DIALOG_NANDINFO             165
#define IDC_COMBO_TYPE                  1001
#define IDC_RECONNECT                   1002
#define IDC_VERSION                     1003
#define IDC_STATIC_DDRFile              1004
#define IDC_COMPORT                     1005
#define IDC_LIST1                       1007
#define IDC_TYPE                        1008
#define IDC_CHECK1                      1010
#define IDC_COMBO1                      1011
#define IDC_COMBO_DDR                   1012
#define IDC_STATIC_DDR_PAR              1013
#define IDC_SPI_DOWNLOAD                1014
#define IDC_SPI_VERIFY                  1015
#define IDC_SPI_READ                    1016
#define IDC_SPI_ERASEALL                1017
#define IDC_SPI_BROWSE                  1018
#define IDC_RADIO1                      1019
#define IDC_MMC_TYPE_A                  1019
#define IDC_MTP_ENABLE                  1019
#define IDC_ERASE_RADIO1                1019
#define IDC_RADIO2                      1020
#define IDC_ERASE_RADIO2                1020
#define IDC_RADIO3                      1021
#define IDC_RADIO4                      1022
#define IDC_MTP_M3                      1022
#define IDC_MMC_EXECADDR_A              1023
#define IDC_MMC_FLASHOFFSET_A           1024
#define IDC_SPI_DOWNPROGRESS            1026
#define IDC_SDRAM_BROWSE                1028
#define IDC_SDRAM_DOWNLOAD              1029
#define IDC_SDRAM_DOWNPROGRESS          1030
#define IDC_DTB_BROWSE                  1031
#define IDC_SDRAMSTATUS                 1032
#define IDC_SDRAM_NOAUTORUN             1033
#define IDC_SDRAM_AUTORUN               1034
#define IDC_SDRAM_FILENAME              1035
#define IDC_SDRAM_BUFFER_ADDRESS        1036
#define IDC_MMC_IMAGELIST               1037
#define IDC_DTB_FILENAME                1037
#define IDC_SPI_IMAGENAME_A             1038
#define IDC_DTB_BUFFER_ADDRESS          1038
#define IDC_MMC_IMAGENAME_A             1039
#define IDC_MMC_DOWNPROGRESS            1040
#define IDC_MMC_PROGRESS                1040
#define IDC_MMC_ERASEALL                1041
#define IDC_MMC_READ                    1042
#define IDC_MMC_VERIFY                  1043
#define IDC_MMC_DOWNLOAD                1044
#define IDC_SPI_COMBO_ENCRYPT           1045
#define IDC_MMC_FORMAT                  1045
#define IDC_SPI_ENC_E                   1046
#define IDC_SPI_EXECADDR_A              1047
#define IDC_SPI_FLASHOFFSET_A           1048
#define IDC_MMC_COMBO_ENCRYPT           1049
#define IDC_MMC_ENC_E                   1050
#define IDC_SPI_TYPE_A                  1052
#define IDC_SPI_TYPE_A2                 1053
#define IDC_SPI_TYPE_A3                 1054
#define IDC_SPI_TYPE_A4                 1055
#define IDC_SPI_TYPE_A41                1055
#define IDC_SPI_IMAGELIST               1056
#define IDC_NAND_IMAGENAME_A            1057
#define IDC_NAND_TYPE_A5                1058
#define IDC_NAND_TYPE_A4                1059
#define IDC_NAND_TYPE_A3                1060
#define IDC_NAND_TYPE_A2                1061
#define IDC_NAND_TYPE_A                 1062
#define IDC_NAND_COMBO_ENCRYPT          1063
#define IDC_NAND_ENC_E                  1064
#define IDC_NAND_EXECADDR_A             1065
#define IDC_NAND_FLASHOFFSET_A          1066
#define IDC_NAND_DOWNLOAD               1067
#define IDC_NAND_VERIFY                 1068
#define IDC_NAND_READ                   1069
#define IDC_NAND_ERASEALL               1070
#define IDC_NAND_DOWNPROGRESS           1071
#define IDC_NAND_PROGRESS               1071
#define IDC_MTP_BROWSE                  1072
#define IDC_MTP_DOWNLOAD                1073
#define IDC_MTP_MODIFY                  1074
#define IDC_MTP_M1                      1075
#define IDC_MTP_M2                      1076
#define IDC_MTP_DOWNPROGRESS            1078
#define IDC_MTP_A0                      1079
#define IDC_MTP_A1                      1080
#define IDC_NAND_IMAGELIST              1080
#define IDC_MTP_A2                      1081
#define IDC_MTP_M4                      1082
#define IDC_PROGRESS1                   1082
#define IDC_OTP_M0                      1083
#define IDC_EDIT1                       1083
#define IDC_SPI_BLOCKS                  1083
#define IDC_READ_BLOCKS                 1083
#define IDC_MTP_M0                      1083
#define IDC_FORMAT_SPACE                1083
#define IDC_USBEDIT1                    1083
#define IDC_SPIREAD_BROSWSE             1084
#define IDC_READ_BROSWSE                1084
#define IDC_READ_STARTBLKS              1085
#define IDC_SPI_FILENAME2               1086
#define IDC_READ_FILENAME2              1086
#define IDC_SIZENAME                    1087
#define IDC_MMC_BROWSE                  1088
#define IDC_MTP_COMBO_ENCRYPT           1089
#define IDC_MMC_TYPE_A2                 1090
#define IDC_MMC_TYPE_A3                 1091
#define IDC_MMC_TYPE_A4                 1092
#define IDC_PACK_IMAGELIST              1093
#define IDC_PACK_IMAGENAME_A            1094
#define IDC_PACK_TYPE_A                 1095
#define IDC_PACK_TYPE_A2                1096
#define IDC_PACK_TYPE_A4                1097
#define IDC_PACK_TYPE_A3                1098
#define IDC_PACK_ENC_E                  1099
#define IDC_PACK_COMBO_ENCRYPT          1100
#define IDC_PACK_EXECADDR_A             1101
#define IDC_PACK_FLASHOFFSET_A          1102
#define IDC_PACK_ADD                    1103
#define IDC_PACK_MODIFY                 1104
#define IDC_PACK_DELETE                 1105
#define IDC_PACK_OUTPUT                 1106
#define IDC_PACK_BROWSE                 1107
#define IDC_PACK_DOWNPROGRESS           1108
#define IDC_PACK_TYPE_A5                1109
#define IDC_NAND_STATUS                 1111
#define IDC_MMC_STATUS                  1112
#define IDC_SPI_STATUS                  1113
#define IDC_PACK_STATUS                 1114
#define IDC_MTP_DISABLE                 1115
#define IDC_LOCK_COMMENT                1117
#define IDC_CHECK_LOCK_ENABLE           1118
#define IDC_NAND_BROWSE                 1119
#define IDC_MTP_PSTATIC                 1120
#define IDC_STARTSIZENAME               1121
#define IDC_PACK_TABCONTROL             1124
#define IDC_PACK_MTP_M1                 1126
#define IDC_PACK_MTP_M2                 1127
#define IDC_PACK_MTP_M3                 1128
#define IDC_PACK_MTP_ENABLE             1129
#define IDC_PACK_MTP_DISABLE            1130
#define IDC_PACK_MTP_A0                 1131
#define IDC_PACK_MTP_A1                 1132
#define IDC_PACK_MTP_A2                 1133
#define IDC_PACK_CHECK_LOCK_ENABLE      1134
#define IDC_PACK_MTP_COMBO_ENCRYPT      1135
#define IDC_PACK_MTP_MODIFY             1136
#define IDC_PACK_MTP_M0                 1137
#define IDC_TAB_LOCK_COMMENT            1138
#define IDC_MTP_STATUS                  1140
#define IDC_EDIT3                       1141
#define IDC_ERASE_STARTBLKS             1142
#define IDC_ERASE_BLOCKS                1143
#define IDC_ERASE_STARTSIZENAME         1144
#define IDC_ERASE_SIZENAME              1145
#define IDC_ERASE_INFO                  1146
#define IDC_STATIC_DTB                  1147
#define DC_STATIC_DTB2                  1148
#define IDC_STATIC_DTB2                 1148
#define IDC_DTB_EN                      1149
#define IDC_FAST_IMAGENAME              1150
#define IDC_FAST_BROWSE                 1151
#define IDC_FAST_TYPE_STATIC            1152
#define IDC_RADIO_FAST_NAND             1153
#define IDC_RADIO_FAST_SPI              1154
#define IDC_RADIO_FAST_eMMC             1155
#define IDC_BTN_FAST_START              1156
#define IDC_FAST_PROGRESS1              1157
#define IDC_FAST_PROGRESS2              1158
#define IDC_FAST_PROGRESS3              1159
#define IDC_FAST_PROGRESS4              1160
#define IDC_FAST_PROGRESS5              1161
#define IDC_FAST_PROGRESS6              1162
#define IDC_FAST_PROGRESS7              1163
#define IDC_FAST_PROGRESS8              1164
#define IDC_FAST_CHKD1                  1165
#define IDC_FAST_CHKD2                  1166
#define IDC_FAST_CHKD3                  1167
#define IDC_FAST_CHKD4                  1168
#define IDC_FAST_CHKD5                  1169
#define IDC_FAST_CHKD6                  1170
#define IDC_FAST_CHKD7                  1171
#define IDC_FAST_CHKD8                  1172
#define IDC_FAST_FILE_STATIC            1173
#define IDC_STATIC_FAST_MSG1            1174
#define IDC_STATIC_FAST_MSG2            1175
#define IDC_STATIC_FAST_MSG3            1176
#define IDC_STATIC_FAST_MSG4            1177
#define IDC_STATIC_FAST_MSG5            1178
#define IDC_STATIC_FAST_MSG6            1179
#define IDC_STATIC_FAST_MSG7            1180
#define IDC_STATIC_FAST_MSG8            1181
#define IDC_STATIC_FAST_MSG9            1182
#define IDC_STATIC_GROUP_DEVICE         1182
#define IDC_STATIC_FAST_DEV1            1183
#define IDC_STATIC_FAST_DEV2            1184
#define IDC_STATIC_FAST_DEV3            1185
#define IDC_STATIC_FAST_DEV4            1186
#define IDC_STATIC_FAST_DEV5            1187
#define IDC_STATIC_FAST_DEV6            1188
#define IDC_STATIC_FAST_DEV7            1189
#define IDC_STATIC_FAST_DEV8            1190
#define IDC_STATIC_FAST_DEV9            1191
#define IDC_BUTTON1                     1191
#define IDC_BUTTON2                     1192
#define IDC_IDCOMBO                     1193
#define IDC_COMBO_FAST_ID               1193
#define IDC_RSTBTN                      1194
#define IDC_ALLRSTBTN                   1195
#define IDC_STATIC_NAND                 1196
#define IDC_DOWNLOADSTATUS              4000
#define IDC_DOWNLOADSTATUS2             4001
#define IDC_DOWNLOADSTATUS3             4002
#define IDC_DOWNLOADSTATUS4             4003
#define IDC_DOWNLOADSTATUS5             4004
#define IDC_DOWNLOADSTATUS6             4005
#define IDC_DOWNLOADSTATUS7             4006
#define IDC_DOWNLOADSTATUS8             4007
#define IDC_DOWNPROGRESS                4008
#define IDC_DOWNPROGRESS2               4009
#define IDC_DOWNPROGRESS3               4010
#define IDC_DOWNPROGRESS4               4011
#define IDC_DOWNPROGRESS5               4012
#define IDC_DOWNPROGRESS6               4013
#define IDC_DOWNPROGRESS7               4014
#define IDC_DOWNPROGRESS8               4015
#define IDC_MTP_M11                     4016
#define IDC_MTP_M12                     4017
#define IDC_MTP_SHAFILENAME             4018
#define IDC_PACK_MTP_M11                4019
#define IDC_PACK_MTP_M12                4020
#define IDC_PACK_MTP_SHAFILENAME        4021
#define IDC_NAND_USRCONFIG              4023
#define IDC_STATIC_NANDINFO1            4024
#define IDC_STATIC_NANDINFO2            4025
#define IDC_EDIT_NANDINFO1              4026
#define IDC_EDIT_NANDINFO2              4027
#define IDC_STATIC_FAST_NANDINFO        4028
#define IDC_FAST_NAND_USRCONFIG         4029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
